services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP: bot
    image: it-bot:bot
    container_name: it-bot-bot
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      - APP=bot
      - PYTHONUNBUFFERED=1
      - TZ=UTC
      - LOG_LEVEL=DEBUG
      - TELEGRAM_DEBUG=1
    volumes:
      - ./data:/data
      - ./config.ini:/app/config.ini:ro
      - ./main.py:/app/main.py:ro
      - ./modules:/app/modules:ro
      - ./requirements.txt:/app/requirements.txt:ro
    networks: [npm]


  idk:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP: idk
    image: it-bot:idk
    container_name: it-bot-idk
    restart: unless-stopped
    expose:
      - "8081"
    environment:
      - APP=idk
      - PYTHONUNBUFFERED=1
      - TZ=UTC
    volumes:
      - ./data:/data
      - ./config.ini:/app/config.ini:ro
      - ./idk_webhook.py:/app/idk_webhook.py:ro
      - ./requirements.txt:/app/requirements.txt:ro
    networks: [npm]

networks:
  npm:
    external: true
